import Head from "next/head";
import Script from "next/script";
import { useState } from "react";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  const [val, setVal] = useState("");
  const [data, setData] = useState(null);

  function searchAnime() {
    fetch(`https://api.jikan.moe/v4/anime?q=${encodeURIComponent(val)}`)
      .then((result) => result.json())
      .then(({ data }) => setData(data));
  }

  return (
    <>
      <Head>
        <title>Tugas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="row mt-3 justify-content-center">
          <div className="col-md-4">
            <h1 className="text-center">Search Animes</h1>
            <div className="input-group mb-3">
              <input type="text" className="form-control" placeholder="Movie title.." id="search-input" onInput={(e) => setVal(e.target.value)} value={val} />
              <button className="btn btn-dark" type="button" id="search-button" onClick={searchAnime}>
                Search
              </button>
            </div>
          </div>
        </div>
        <hr />
        <div className="row" id="anime-list">
          {data
            ? data.map((anime, elon) => (
                <div className="col-md-3 my-3" key={elon}>
                  <div className={`${styles.card} card`}>
                    <img src={anime.images.jpg.image_url} className={`${styles.img}card-img-top`} />
                    <div className="card-body">
                      <h5 className="card-title">{anime.title}</h5>
                      <h6 className="card-subtitle mb-2 text-muted">{anime.year}</h6>
                      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        See Detail
                      </button>
                      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h1 class="modal-title fs-5" id="exampleModalLabel">
                                Movie Search
                              </h1>
                              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            
                            {/* modal */}
                            <div class="modal-body">
                              <div class="container-fluid">
                                <div class="row">
                                  <div class="col-md-4">
                                    <img src={anime.images.jpg.image_url} class="img-fluid" />
                                  </div>
                                  <div class="col-md-8">
                                    <ul class="list-group">
                                      <li class="list-group-item">
                                        <h3>{anime.title}</h3>
                                      </li>
                                      <li class="list-group-item">Released: {anime.year}</li>
                                      <li class="list-group-item">Score: {anime.score}</li>
                                      <li class="list-group-item">Duration:{anime.duration}</li>
                                      <li class="list-group-item">episodes:{anime.episodes}</li>
                                      <li class="list-group-item">Synopsis:{anime.synopsis}</li>
                                    </ul>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                                Close
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              ))
            : null}
        </div>
      </div>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous" />
      <Script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous" />
    </>
  );
}