import Head from 'next/head'
import Mountain from '../components/decorations/Mountain'
import Search from '../components/Search'
import Result from '../components/Result'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';
import axios from "axios";



export default function Home() {
  const queer = "nirvana", 
        keys = "vdllPpJUiGgdknayWciy", 
        secret = "vOhXuzHGbUybRKLpPKwHOkGNnMEsNwok";
  const url = `https://api.discogs.com/database/search?q=${queer}&key=${keys}&secret=${secret}`
  const fetchData = (e) => {
    e.preventDefault();
    // setLoading(true);
    axios.get(url).then((response) => {
      console.log(response);
    });
  };
  return (
    <>
      <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Search></Search>
        <Result></Result>
      </main>
      <Mountain ></Mountain>
    </>
  )
}
